### ISSUE TITLE
getStatstics only retrieves stats of a single population

### ISSUE THREAD

**Issue by lkupcsik** [cellengine/cellengine-r-toolkit#96]
Providing multiple population names will only get the stats for the first one, The function doc suggests it should return a single data frame with multiple population's statistics. 

> populations | **Names of populations.** An attempt will be made to find the population by name. If zero or more than one population exists with the name, an error will be thrown. If specified, do not specify populationIds.

I traced it back to [`lookupPopulationsByName()`](https://github.com/cellengine/cellengine-r-toolkit/blob/c39cecdd30a8bb4cf5e397ecfd56638ee60231cc/R/getStatistics.R#L297)

**Comment by zbjornson** [comment]
Thanks for reporting this. I just pushed the fix. Please re-install the latest version of the toolkit:

```R
library("devtools")
install_github("cellengine/cellengine-r-toolkit")
```
